services:
  - type: web
    name: cashcheck
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cashcheck-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: cashcheck-db
    databaseName: cashcheck
    user: cashcheck
    plan: free